### ISSUE TITLE
Error issue with 2.0.8

### ISSUE THREAD

**Issue by 24Clayton** [aussieaddons/plugin.video.afl-video#2644] opened 2020-08-19 08:47 UTC
Is there currently an issue with AFL live? I'm getting an error message everytime I try and click on the live stream it says max retries have been exceeded with a particular URL. can send screenshots

**Comment by andybotting** [comment] 2020-08-19 08:53
@24Clayton I can confirm I also see the issue. Leave it with us to investigate.

**Comment by 24Clayton** [comment] 2020-08-19 08:57
Thanks dude, will do

**Comment by andybotting** [comment] 2020-08-19 09:17
The error was `Connection refused` on port 80 so it looks like we just needed to update some of the auth URLs from http to https which I've fixed in commit a071dc03f5ae022e8539def8bc83b2de5e9b0e70

A new build `2.0.8-2~g4af6715` is available in our development repo that you should try out. If you haven't tried out development repo before, there's some notes about it here https://aussieaddons.com/development/

Let me know how you get on

**Comment by 24Clayton** [comment] 2020-08-19 09:34
Hey, thanks for that. I have installed development repo and updated afl-live. Can confirm the AFL TV live stream is now working. Thank you very much, appreciate it.

**Comment by andybotting** [comment] 2020-08-19 09:42
No problems - thanks for testing.

Will probably push a new build v2.0.9 to the main repository soon, so once that happens, feel free to remove the development repo.

cheers

**Comment by 24Clayton** [comment] 2020-08-19 09:55
Sure, if you would like me to, unless you would like be to continue testing for you - your choice

**Comment by andybotting** [comment] 2020-08-19 10:00
It's up to you, but we always like testers :)

**Comment by 24Clayton** [comment] 2020-08-19 22:13
I'm happy to stay on as a tester, if it's going to be helpful to you? Just let me know what you want me to do and when. All good!

**Comment by BillV151** [comment] 2020-08-20 07:44
I am having trouble getting it to accept my username/password on a new install of the repo development version. Just stays in a loop.

**Comment by andybotting** [comment] 2020-08-20 07:52
Thanks @BillV151 I'll try and reproduce it shortly. In the mean time, could you send us a copy of your log? Do you know how to do that?

**Comment by pinheadmercs** [comment] 2020-08-20 08:23
sorry to hi-jack this thread, but can someone tell me how to re-sort the reply games so that the Quarters play in order from Q1 thru to Q4, I have (I think) tried everything on Kodi the change the order.

**Comment by andybotting** [comment] 2020-08-20 09:36
> sorry to hi-jack this thread, but can someone tell me how to re-sort the reply games so that the Quarters play in order from Q1 thru to Q4, I have (I think) tried everything on Kodi the change the order.

@pinheadmercs Yeah, don't hijack this one. Please file a separate issue. Thanks

**Comment by andybotting** [comment] 2020-08-20 09:39
> Thanks @BillV151 I'll try and reproduce it shortly. In the mean time, could you send us a copy of your log? Do you know how to do that?

@BillV151 I can't reproduce it using Telstra free live pass or in-app purchase login mechanisms. If you're still having trouble can you also create a new issue and maybe include some more details like your subscription type, what platform you're running on and if this is a new issue specific to this new development version. Thanks

**Comment by andybotting** [comment] 2020-08-20 09:40
The original issue was solved, so closing this issue.

cheers

**Closed by andybotting** 2020-08-20 09:40 UTC
