### ISSUE TITLE
Stored token has expired....

### ISSUE THREAD

**Issue by yioryos467** [aussieaddons/plugin.video.afl-video#2630] opened 2019-07-07 03:44 UTC
play.py (47)- AussieAddonsException: Stored token has expired, please try and play this item again. if this error persists please submit an issue on github. My ID works ok on all other addons, it expires 20/01/2020, so I know it is ok.

**Comment by glennguy** [comment] 2019-07-07 05:17
Hi @yioryos467 
Can we please see a debug log from you?

* Enable debug logging in Kodi settings -> system -> logging (don't enable component specific logging though)
* Restart Kodi
* Try to play the stream in AFL add-on
* Go into AFL add-on settings and choose 'send user report'
* Write back here with the issue number given

Thanks

Glenn

**Comment by yioryos467** [comment] 2019-07-07 05:39
Hi Glen,

I had another issue come up 5162 which I submitted as I was trying to get
into Live Matches.... the actual issue no. for this problem is 5165.

Thanks
George

**Comment by glennguy** [comment] 2019-07-07 09:51
Thanks for that George.

Do you happen to have multiple services/phone numbers connected to the Telstra ID that you're using?

**Comment by yioryos467** [comment] 2019-07-07 11:32
Yes, I use the same id on my phone, tablet plus 2 more Android boxes.

**Comment by yioryos467** [comment] 2019-07-07 11:35
Even though I have it on multiple devices, I've never had any issues
before, also playing 2 at the same time and it's been ok.

**Comment by glennguy** [comment] 2019-07-07 12:39
No what I mean is have you attached two or more services/mobile numbers to your Telstra ID - nothing to do with the Kodi addon i.e if you log in at telstra.com what/how many services are linked in there, and are they all eligible for the sports pass offer? 

There might be some extra logic that we need to put in when looking at the attached services and eligibility. I'll have a closer look at what it looks like for my ID/accounts tomorrow and see if I can work it out. My bet atm is that maybe you had a service that was eligible and has now expired (like a lapsed prepaid or something), and the addon unaware keeps choosing that one to try and register.

Your other devices would be running on a stored token that has yet to expire. If you were to clear to stored token in the settings you'd likely see the same problem (so don't do that just yet :) )

Thanks for your help in diagnosing this btw, it's very hard to account for all possible situations that could go wrong and we can't put most of the useful responses from the Telstra servers in the log as it contains personal info.

**Comment by yioryos467** [comment] 2019-07-07 12:46
Ok, now that makes sense, I had a prepaid mobile and tablet which I
cancelled last week but I thought my existing mobile should cater for the
free pass since I pay more than $100 each month. I might have to chase this
up with Telstra tomorrow and let you know.

**Comment by glennguy** [comment] 2019-07-07 12:50
No need to chase up, it's almost definitely the addon that needs fixing. On the offical app if you sign in over wifi you get to choose which mobile number you're going to use, whereas the addon selects automatically (incorrectly it seems in this case) I'm pretty sure there's data in there for expiry dates for each service/offer, my assumption was that the API wouldn't provide an 'offer' that has expired already. We'll get it sorted for next round 😄

**Comment by yioryos467** [comment] 2019-07-07 12:52
Ok, leave it with you.

**Comment by glennguy** [comment] 2019-07-12 06:16
@yioryos467 

Install this zip: https://github.com/aussieaddons/plugin.video.afl-video/archive/check_entitlements.zip and give it a try. A bit of a stab in the dark but I'm hopeful that it will fix the issue for you.

The installed version will be 0.0.0, so it will auto update back to the current version when it next checks. If you've already signed in successfully it won't matter though. Once we have a working solution it will end up in the master branch shortly after anyway.

**Comment by yioryos467** [comment] 2019-07-12 06:56
Hi Glenn,

No go, same error.... I uninstalled the addon and ran your zip, I checked
the version straight away and it was 1.8.3.

Regards
George

**Comment by glennguy** [comment] 2019-07-12 07:28
I've made some more updates to log what's going on at your end (this won't fix the issue but I might be able to identify what needs fixing).

Can you redownload the zip from the link and install/try again. It will fail, but once it does can you submit another error report and write back with the issue number? Thanks heaps.

**Comment by yioryos467** [comment] 2019-07-12 07:47
Issue 5181

**Comment by glennguy** [comment] 2019-07-12 08:07
Thanks again for that.

One more update, I think I've found what to look for. So can you redownload again? It might work this time. Either way though, could you please submit another error report after attempting?

**Comment by yioryos467** [comment] 2019-07-12 08:26
Issue 5182, I got the same error.

**Comment by glennguy** [comment] 2019-07-12 09:34
Looks like on your last try the zip didn't install properly or it was the previous version downloaded.... Not to worry as it doesn't look like there's a way we can detect beforehand if it will work or not.

So the next solution is to try registering the live pass on each of your services until 1 works.

Try redownloading the zip again, installing again and seeing how you go. Thanks for your patience.

**Comment by glennguy** [comment] 2019-07-12 09:36
Actually just wait a couple of minutes. I think github caches that link and it takes around 5 minutes for the changes to end up in there.

**Comment by glennguy** [comment] 2019-07-12 09:37
Ok looks good to go now

**Comment by yioryos467** [comment] 2019-07-12 09:42
I had to go out to help someone with their laptop, I'll be back around
9.30-10pm. I'll download it again and try it and let you know the outcome.

George

**Comment by glennguy** [comment] 2019-07-12 09:47
Oh no, your life sounds like mine haha

**Comment by yioryos467** [comment] 2019-07-12 10:13
Yep... I was in IT for 24yrs... do you think the calls stopped when I gave
it all up? It got worse... lol people kept ringing me to help them out coz
they knew I wasn't working... so they assumed I had spare time. I can
sympathise with you as I know what you're going through....

**Comment by yioryos467** [comment] 2019-07-12 12:35
Issue 5188, got the same error.

Sorry  just got back.

**Comment by glennguy** [comment] 2019-07-13 05:22
Yeah when you're known as "the one that's good with computers" its open season. Doing this stuff though is fun and satisfying so I don't mind!

One last update for some more logging info when you have time. I think I'm looking in the right spot now.

**Comment by yioryos467** [comment] 2019-07-13 06:57
Issue 5201...

Same error... i also checked the version and it is 0.0.0

George

**Comment by glennguy** [comment] 2019-07-13 12:20
Thanks for that. I've found a key difference in the response in your log. I'll bang up another change to test in the morning, fingers crossed!

**Comment by yioryos467** [comment] 2019-07-13 12:27
Ok, all good, sorry to put you through all this...

**Comment by glennguy** [comment] 2019-07-14 01:05
No need to apologise!

Just pushed another update, I'm on the right track I think.

**Comment by yioryos467** [comment] 2019-07-14 04:32
Sorry Glenn, I was out...

Same error, issue 5208

**Comment by glennguy** [comment] 2019-07-14 05:03
All good.

One more change again when you get a chance.

**Comment by glennguy** [comment] 2019-07-14 06:37
Can you try something for me?
Install the mobile app (and if you haven't clear the data/cache from it to clear your live pass) and try to activate the live pass over wifi, not mobile data. You'll have to enter your Telstra ID the same as the addon.

**Comment by yioryos467** [comment] 2019-07-14 08:39
Ok, did the mobile app install over wifi... i put my Telstra ID in then it
prompted me to select the mobile number as it displayed all 3 services I
had.... as I unmentioned, 2 were cancelled and I selected my current mobile
no.

Also ran the update again, it did not work but got a different error....

play.py (44) - TelstraAuthException: Live pass registration failed...

Issue 5212 and 5213... did it again, forgot the issue no.... lol

**Comment by glennguy** [comment] 2019-07-14 09:47
Forgot to ask - on your mobile can you successfully watch live matches/AFL.tv? (you can without activating but its only a 90 second preview)

Looking at the log your current mobile no is 614477XXXXX (that's all I can see, I made sure to blank out the last 5 digits in the log for privacy) - is that right? That's the only number that supposedly is eligible.

**Comment by yioryos467** [comment] 2019-07-14 09:53
It won't let me view AFL.TV unless I log in. I click on it and its says
free for Telstra customers... then it says that I've successfully activated
my live pass but it won't start, just keeps looping around.

**Comment by yioryos467** [comment] 2019-07-14 09:55
And yes, that is the number I have, 0447756768, if you need to talk, call
me if it helps.

George

**Comment by glennguy** [comment] 2019-07-14 10:29
If you exit the app/reopen is it then logged in? The live pass logo in the top right corner should be green if so. I'm also curious to know if it will activate properly over mobile data.

As far as I can see the live pass should be activating but when you query the API it can't seem to find a record of it. Maybe there's an issue on their end - not being able to get the mobile app to work would confirm this. If that's the case then our efforts are in vein!

Another thing to try would be creating a new Telstra ID using another email address and adding the number to that ID and seeing if the problem is resolved.

**Comment by yioryos467** [comment] 2019-07-14 10:55
Can you call me....

**Comment by yioryos467** [comment] 2019-07-14 11:26
I did as you instructed,  it stayed logged in after I exited.  I also
cleard all data and cache and started the process with mobile data only, it
asked for mobile, so I selected my current mobile no,  it worked all ok. I
was able to create a new Telstra Id wirh different email, assigned the
mobile to it and all ok. I was able to log onto the app with the new
details ok. I tried it on my kodi and guess what, I got the same error,
that the stored login token has expired.

I made sure I upgraded AFL Video to v1.9.2-3.... removed stored tokin and
added new id but.... it didn't work.

**Comment by yioryos467** [comment] 2019-07-14 11:27
yioryos467@bigpond.com
Geoxan6768

yioryos467@gmail.com
Geoxan6768

**Comment by glennguy** [comment] 2019-07-18 05:45
Hey George,

I've tried a bunch of times and can't get any different response from your gmail ID, the live pass won't activate properly using the Telstra ID logon. My best guess is that it's a system issue on their end. In the past having home phone/broadband on the same account prevented users from activating the live pass, maybe that issue is what's at play here...

Another way to get your live pass onto your Telstra ID (if you don't feel like typing out the 32 characters) is to link it within the mobile app. Press on the green live pass icon in the top right, go to AFL Live Pass Subscription and there should be a button to 'Link Your Live Pass' and put your Telstra ID in there.

Thanks heaps for your patience in trying to get this sorted. I'll close the issue now, but if there's any further problems let us know!

**Closed by glennguy** 2019-07-18 05:45 UTC

**Comment by robmOz** [comment] 2019-08-31 06:10
I'm getting this same error. "Stored token has expired". Is there a fix?
