### ISSUE TITLE
Live AFL streams not working for me with v1.9.1

### ISSUE THREAD

**Issue by 24Clayton** [aussieaddons/plugin.video.afl-video#2614] opened 2019-03-22 00:08 UTC
Hi, I'm still having issues getting v1.9.1 to work for live streams. It tries to play but then can't (for whatever reason). I've tried updating, uninstalling and re-installing, but still nothing. Any other suggestion?
Cheers.

**Comment by glennguy** [comment] 2019-03-22 00:33
Can we see a debug log from you?

* Turn on debug logging (in settings/system/logging, or press ctrl+shift+d)
* Restart Kodi
* Recreate the issue
* Submit user report from afl-video settings in the debugging tab
* Write back here with the issue number that it gives you

Thanks

**Comment by 24Clayton** [comment] 2019-03-22 01:20
Cheers for the reply. I believe I have now done all that you asked. The issue number it gave me was 4039. Again, cheers for your assistance!

**Comment by 24Clayton** [comment] 2019-03-22 02:22
Just so you are aware, I have also wiped my system and reinstalled kodi (and addons). Unfortunately, I still get the same issue

**Comment by glennguy** [comment] 2019-03-22 03:10
Thanks for the log!

We're getting a HTTP 503 response from the widevine license server, which I can't reproduce on my end. I've tested with my libreelec on rpi3 (using 18.1 RC1, build date is only 11 days before yours so I don't think that's likely to affect but if we can't solve it I'll upgrade and see)

The most likely cause would be that you have an old or incompatible widevinecdm library installed. I've just removed mine and reinstalled through the addon and it works so let's try that.

Just remove /storage/.kodi/cdm/libwidevinecd.so (or rename it if you're worried), then restart Kodi and try to play afl.tv. It will prompt you to redownload, which you accept. I had to try playback again, then it worked. Let me know how you go.

**Comment by 24Clayton** [comment] 2019-03-22 03:14
Wow, thank you so much for such a detailed reply and for the lengths you have gone to. I will do this as soon as I've picked up my children from school and return home.
Cheers mate!

**Comment by 24Clayton** [comment] 2019-03-22 05:16
Hi,
I've had no success so far in being able to locate /storage/.kodi... through Win explorer, I've tried SSH but I get timed out (or something like that) and I can find the location using the Filesystem of Kodi but can't delete/change name of anything and can't locate ibwidevinecd.so just 2 files with lots of AlphaNumerals.
Sorry

**Comment by glennguy** [comment] 2019-03-22 05:37
Download WinSCP -  https://winscp.net/eng/download.php , it will make this very easy :)
username is root, password is libreelec

**Comment by glennguy** [comment] 2019-03-22 05:47
And make sure to show hidden files: ctrl + alt + h

**Comment by 24Clayton** [comment] 2019-03-22 06:29
I did all the things that you suggested, my first issue was that I didn't have SSH enabled on Libreelec; sorry. At this stage (watching AFL TV) it seems to be working brilliantly. True test I guess will be tonight's match Pies v Cats (GO CATS!!!) Thank you ever so much, you're a legend.
Clayton
PS, just so you are aware I had to change the resolution from MAX to 1080p otherwise it was very 1970s vision (blurry)

**Comment by glennguy** [comment] 2019-03-22 06:51
Hey happy to help add glad we got there! Thanks for working through it with me. It's good to know that's what the issue was.

With the resolution - that's interesting to know as well, I'll have to do some testing. With that said, we don't maintain inputstream.adaptive, that's for the Kodi devs. However, if you have any further resolution issues just put a large number in minimum bitrate - 10000000 should do it. Also, if you're running in a small window like on the desktop it will take that into account unless you change the setting to ignore it.

**Comment by hawksta** [comment] 2019-03-22 09:08
I'm on Android box running Kodi 18.1 but only get sound and no video.  What do i do

**Comment by hawksta** [comment] 2019-03-22 09:23
I can watch replays no problem.  But live has no video, just sound

**Comment by glennguy** [comment] 2019-03-22 09:52
@hawksta Please follow the instructions in the second comment and report back

**Comment by glennguy** [comment] 2019-03-22 09:58
Just having a think without seeing the logs.... It could be that your Android device is a cheap Chinese one without any widevine (DRM) certification, or at least only the lower level 3.

You can get an app from the play store - DRM info to check this.

Try going into inputstream.adaptive settings (can get there easily from afl-video settings) and seeing both decoders to 480p to see if you get video...

**Comment by hawksta** [comment] 2019-03-22 10:35
Wideine CDM
Vendor Google
Version 1.0
Security level L3

So what does this mean....i tried turning the settings inn both to 480p and it still does not work
I am running an X96 mini 2G16G

**Comment by hawksta** [comment] 2019-03-22 10:40
Wideine CDM
Vendor Google
Version 1.0
Security level L3

So what does this mean....i tried turning the settings inn both to 480p and it still does not work
I am running an X96 mini 2G16G

**Comment by glennguy** [comment] 2019-03-22 10:55
It means the max resolution your device will do is 480p.

Try this:
go back to the inputstream.adaptive settings, and put 500000 for the max bitrate. Try viewing the live stream. You should hopefully get a low res video playing.

**Comment by glennguy** [comment] 2019-03-22 10:56
If that isn't giving you a picture, then I'll need to see a debug log to help you further.

**Comment by hawksta** [comment] 2019-03-22 11:01
Nope sorrythat did not work either.... how do i send you a debug log

**Comment by glennguy** [comment] 2019-03-22 11:02
instructions are in the second comment of this thread

**Comment by jwils1691** [comment] 2019-03-22 11:11
Hi Glennguy, getting a play.py (47) - HHTPError: 404 Client error: not found for URL: http://player.ooyala.com/sas/player_api/v1/authorization/embed_

Had no issues last season, installed new kodi and fresh install of AFL Video just now but still getting the same problem even after fresh installs. 

Any help much appreciated.

**Comment by glennguy** [comment] 2019-03-22 11:17
@jwils1691 can you check that your subscription settings are correct? 

If you're still having issues, please provide a debug log. Instructions in the second post.

**Comment by glennguy** [comment] 2019-03-22 11:22
@jwils1691 now that I think about it there was an issue where accounts linked to subscriptions became unlinked earlier this year, if that's how you're trying to access the service. Go into the AFL app on your phone and make sure it's linked. If not, link again.

**Comment by hawksta** [comment] 2019-03-22 11:23
Issue 4047 sent

**Comment by glennguy** [comment] 2019-03-22 11:43
Still looking @hawksta 

In inputstream.adaptive do you have the override HDCP status turned on? Try toggling and see if it helps...

**Comment by jwils1691** [comment] 2019-03-22 11:47
@glennguy interesting, I did a quick download of Kodi on my Android and install of AFL Video, used the same login credentials and it worked straight away. 

i will have a bit more a tinker on my end and if i cant work it out on the PC then ill send a log through.

**Comment by hawksta** [comment] 2019-03-22 12:00
Where do i find input stream adaptive

**Comment by glennguy** [comment] 2019-03-22 12:02
from an earlier reply:
`Try going into inputstream.adaptive settings (can get there easily from afl-video settings) and setting both decoders to 480p to see if you get video...`

**Comment by hawksta** [comment] 2019-03-22 12:09
Min Bandwidth 0
Max bandwidth 500000
Max Res general decoder 480p
Max res secure decoder 480p
Stream selection Auto
Media All
Override HDCP on
Ignore display resolution Off

Still no good.....

**Comment by jwils1691** [comment] 2019-03-22 23:01
Hi @glennguy still no luck on the PC but running fine on my Android. Sent through the automatic error report, number 4051. If there is anything else i can do on my end to help let me know.

**Comment by glennguy** [comment] 2019-03-22 23:15
@hawksta 
I've managed to reproduce on my old phone, and hopefully have a solution for you! Go into Kodi's settings, Player, and make sure you're set to advanced or expert settings (bottom left of screen for default Kodi skin). Then have a look in the videos tab under the Processing heading for the 2 'Allow hardware acceleration' settings, and make sure they're turned on. I had audio only when they were turned off.

@jwils1691 
Double check your subscription type is definitely the right type and also while in the settings go to the debugging tab and select Remove Stored Login Token, then try again.

**Comment by glennguy** [comment] 2019-03-22 23:27
@jwils1691 
Been looking some more and I don't think that's the issue.
I can visit that url in my browser and get a HTTP 200 response. 
Do you have any adblockers installed? From what I've seen some of them block ooyala.com.

**Comment by jwils1691** [comment] 2019-03-23 00:19
@glennguy im at a loss. No adblockers, and everything kodi related has been allowed, tried running as administrator and still same error. Cant for life of me work out why its fine on my Android but not my PC. Have made sure all settings are identical, all connected to the same network etc.  

I clicked the URL i posted above and it does come back as a 404 but i can access the ooyala.com homepage.

**Comment by glennguy** [comment] 2019-03-23 00:57
@jwils1691 
instead of clicking the link above (which will always 404) try [this one](http://player.ooyala.com/sas/player_api/v1/authorization/embed_code/Zha2IxOrpV-sPLqnCop1Lz0fZ5Gi/F2bGFoaDE61wxwObeg_OXIQR80l7U631?device=html5&domain=http://www.ooyala.com&supportedFormats=m3u8,dash&embedToken=https%3A//player.ooyala.com/sas/embed_token/Zha2IxOrpV-sPLqnCop1Lz0fZ5Gi/F2bGFoaDE61wxwObeg_OXIQR80l7U631%3Fapi_key%3DZha2IxOrpV-sPLqnCop1Lz0fZ5Gi.Gq2TW%26expires%3D1553294994%26signature%3DEr9gRmVI0AJjYowon0%252FAq6TXfSepz%252BU52FgjghU8l7w%26account_id%3Dmis-uuid-75fa96e8ebbf278ea228e245dedba57a) taken from your issue report.

Is your android device connected to the same network as your PC, or was is through mobile data?

**Comment by jwils1691** [comment] 2019-03-23 03:11
@glennguy clicking the link you have there gives me a 404 error too. (404 Not Found 199.244.115.93 - no redirects at this IP)

Android device connected to the same network as PC (android wireless, PC ethernet). 

Im now getting an error on my Android this morning. Replays are working but when i go to watch live i get - play.py (47) - AussieAddonsException: Failed to obtain secure token: this is not a recognized embed code. check your subscription is valid. 

Its all certainly sounding like an authorization issue but weird i can watch replays and was able to live stream last night on mobile only. I can also log into the AFL app on my android and watch with no issue. 

Used your addon all throughout last season and loved it (got family and friends on too) hopefully i can sort this issue and cancel my Kayo Sports.

**Comment by 24Clayton** [comment] 2019-03-23 03:25
Hi @glennguy, thanks for your assistance yesterday. I was able to watch last nights game without any issue. However, today I go to watch the live game and AFL Video throws up two error messages (attached). I have removed the stored token (as you mentioned in an above post) but no joy.
Any ideas?
Cheers,
 - Clayton

**Comment by 24Clayton** [comment] 2019-03-23 03:52
Not sure if this fixed the issue, but I re entered my password (although it was correct) and live matches are now playing. Cheers

**Comment by BM183** [comment] 2019-03-23 04:13
I had to reinstall and re-enter my data to get the new version playing streams again. Was giving token errors before that (UUID code method).

Now, the max stream resolution I can get is 576p. What's the best afl stream resolution, I remember it being better? Have tried increasing the min bandwidth, same stream loads. Any ideas how to force the high res?

**Comment by 24Clayton** [comment] 2019-03-23 04:24
@bm183 my resume is set to 1080p, which I think actual res is hovering between that and 720

**Comment by glennguy** [comment] 2019-03-23 04:31
@BM183 max res is 1024x576, that's all we get for what we pay :/

@jwils1691 today's error is not related, but seems to have resolved itself. Could have been an issue on their end. As far as your issue goes, clicking the link still works for me. Is it possible you've had some ad blocking software that's modified your HOSTS file? Have a look at `C:\Windows\System32\Drivers\etc\hosts` in notepad and see if it isn't just the default (which is around 20-30 lines of examples). 
Also, are you PC and Android both connected with the same network settings (gateway and DNS)?

@24Clayton seems to have been an intermittent issue, let's hope it's all good for tonight!

**Comment by 24Clayton** [comment] 2019-03-23 04:35
@glennguy yeah, although I'm just happy I got to watch the Cats beat the Pies...

Side note: I can't complain about the resolution, mine is really good

**Comment by hawksta** [comment] 2019-03-23 05:30
Thank you so much @glennguy ..... that was the trick and it is working like a charm....

**Comment by hawksta** [comment] 2019-03-23 05:38
As a note i have set everything back to defaults in the app with bit rates and resolution and I'm getting great results

**Comment by 24Clayton** [comment] 2019-03-23 05:51
Just confirming that I have updated Libreelec to 9.0.2 (Kodi 18.1) and AFL Video (Inc live streaming) working fine. I note that you @glennguy have pushed v1.9.2, will update soon and report back with anything I find (if you're happy for me to do that?)

**Comment by glennguy** [comment] 2019-03-23 05:58
@hawksta great to hear, thanks for sticking with it!

@24Clayton of course, please let us know if there's any more issues.

With regards to resolution everyone - it's only ever been a max of 1024*576 over the last 4 seasons but Kodi can cause confusion as Kodi will report to the skin anything over 540 pixels high as at least 720p resolution, so your skin will likely say 720p.

**Comment by RoadKill2** [comment] 2019-03-23 06:13
Need help i have upgrade kodi to 18.1 on my win10 pc not sure if had to to that ? i have tried the steps above but no joy i keep getting the play.py(45) - TelstraAuthException No eligible services error
the app was working fine last week 
Also the same Error on my Android tv box but its still running Kodi 17.6
The App is working on my Android phone with no problems
Help Please

**Comment by glennguy** [comment] 2019-03-23 06:32
@RoadKill2 
We have a few options:

1:
Using the paid/linked subscription type in the addon.
Go into the app on your Android/iPhone, make sure your live pass is activated and then in the live pass menu (top right) and in 'AFL Live Pass Subscription' click on 'Link your live pass'' and follow the instructions

or
2:
using the free subscription type in the addon.
go to telstra.com in your browser, login to my telstra and check that your eligible phone account is actually in there (we've had reports of it 'forgetting') and add it if not.

or
3:
using the in app subscription/manual type in the addon:
Go into the app on your Android/iPhone, make sure your live pass is activated and then in the live pass menu (top right) and in 'AFL Live Pass Subscription'. Scroll down and find the UUID token number. Further instructions from the menu item in the settings 'IAP help'

**Comment by glennguy** [comment] 2019-03-23 06:52
And @RoadKill2 - yes you need Kodi 18 to be able to watch the live games so you will need to update your other devices.

**Comment by RoadKill2** [comment] 2019-03-23 07:09
Ok  i tried step 1 but could not see the Link your live pass button also this is a free telstra pass on my mates phone i just spoke him on phone and he could find the Link your live pass button on his phone but live pass is working on his apple phone & my Android phone.
Can i use step 3 for the free telstra  pass ?
and thanks for tip on having to upgrade Kodi to 18

**Comment by 24Clayton** [comment] 2019-03-23 08:08
@glennguy what is the best way to update to 1.9.2 on Libreelec (raspi)? I can't see the update in the repository or in the update add-ons section.
Cheers

**Comment by 24mchours** [comment] 2019-03-23 08:25
Hi guys, having the same issue as the opening poster; log #4176.

Would greatly appreciate any assistance to get this going on PC (win 10).

Thank you very much!

**Comment by glennguy** [comment] 2019-03-23 08:48
@RoadKill2 no problems :)

@24Clayton you need to get kodi to check for updates. in the estuary skin, go to addons, click the opened box icon in upper left, install from repository, highlight our repo and right click/long press/press 'c' and select check for updates. That should do the trick

@24mchours it looks like you've got the UWP (windows store) version of Kodi. You'll unfortunately need to uninstall it and install the regular windows release to get DRM working.

**Comment by 24Clayton** [comment] 2019-03-23 09:35
@glennguy 👍🏾 Thanks again dude. Update worked like a charm. Can confirm 1.9.2 works well on Libreelec 9.0.1 (Kodi 18.1).

**Comment by randommonth** [comment] 2019-03-23 10:33
Hi @glennguy, I got AFL video working on my first Rasp Pi (running OSMC) by upgrading to an OSMC nightly, which worked well... I'm back again with an issue on my second Rasp Pi... This one is running Retropie which I just updated all packages on, which upgraded Kodi to 18.1. 
I then tried to run AFL Video 1.9.2 but it fails when trying to pull the live stream. I tried the advice above to delete the libwidevine file, which I did and the system reinstalled it, but the issue persists.

My error log is 4191.

Thanks in advance...

**Comment by andybotting** [comment] 2019-03-23 10:50
@randommonth I can see this in your log file:

```
ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/home/pi/.kodi/cdm/libwidevinecdm.so)
ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
```

I can see that earlier in your log file, it does seem to successfully download the widevine library. I'd recommend you check to make sure the library file does exist and looks ok (/home/pi/.kodi/cdm/libwidevinecdm.so)

**Comment by glennguy** [comment] 2019-03-23 10:50
Hey @randommonth
I can see this in the log: `ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/home/pi/.kodi/cdm/libwidevinecdm.so)`
Definitely to do with that then.
Usually it's caused by having the wrong libwidevinecdm for your system. It should download the one here: https://github.com/matthuisman/decryptmodules/raw/master/widevine/1.4.9.1088-linux-armv7.so
Needs to be renamed of course.


If you're still having troubles, can you put up a log showing the process of downloading libwidevinecdm?

**Comment by glennguy** [comment] 2019-03-23 10:55
Just an idea - the download process normally works fine on libreelec as the user is root. Can you check libwidevinecdm has execute permissions for kodis user?

**Comment by Ado78** [comment] 2019-03-23 14:24
Made an account just to say thanks to you guys who made this and are here helping out guys having problems with it! Been using it the past couple years and I was having issues getting mine working today but thanks to these comments and replies got it working again :) (silly me I was trying to use the windows app)

**Comment by randommonth** [comment] 2019-03-23 22:00
Thanks for the advice @glennguy and @andybotting, I downloaded the libwidevine file that @glennguy suggested and it looks like it's working. I've only tried it on the 'AFL TV' live feed but will confirm later with the live games this afternoon. You guys have the best turnaround in issue resolution!! Thanks!

**Comment by releasemenow** [comment] 2019-03-24 00:05
Having the same issue as some  are describing here 
Running 2 MI boxes with the latest 1.9.2  vs on the same  telstra account 
One box works fine,so no problems,but the other wont stream live games at all
Have uninstalled  and reinstalled Kodi 18.1 and updated to 1.9.2 but no luck
Help on this issue would be greatly appreciated
The debug log is  4196

**Comment by andybotting** [comment] 2019-03-24 00:27
@releasemenow Your log indicates some sort of timeout. My first thought is that is seems more like a network-related issue than platform. Are both of your boxes on the same network with the same config? E.g. no VPNs or funny business?

**Comment by andybotting** [comment] 2019-03-24 00:31
We believe the actual issue created here has now be resolved, so I'm going to close it. 

For those looking for more general support, I'd recommend you join our Slack channel (see http://aussieaddons.com/contact/ for details), or for specific issues, file a new issue.

Thanks guys.

**Closed by andybotting** 2019-03-24 00:31 UTC
