### ISSUE TITLE
Stream Will Not Load

### ISSUE THREAD

**Issue by modano182** [aussieaddons/plugin.video.afl-video#2611] opened 2019-03-16 07:38 UTC
Hi guys - noticing that when I stream AFL TV it loads and starts streaming fine, but today when I clicked on the other Live channel in the Women's AFL game, Kodi just loads forever and never shows the stream. Basically I get stuck with the blue circle loading icon, then have to exit Kodi to reuse again.

**Comment by modano182** [comment] 2019-03-16 08:20
Just to add to this, the error message that pops up after trying to load the video for 2 or 3 minutes is:

Playback Failed
One or more items failed to play. Check the log for more information about this message.

**Comment by glennguy** [comment] 2019-03-17 00:13
Hi @modano182 

I'll check later today when the aflw games are on.

If you have this issue again can you send us a debug log?

Steps are:
* Turn on debug logging - you can do this in Kodi settings > system > logging, or if you have a keyboard press crtl + shift + d
* restart Kodi
* recreate the error by trying to play the match again
* submit the log using the menu option 'Send error report' in the afl addon settings' Debugging tab.
* write back here with the issue number it gives you

Thanks!

**Comment by modano182** [comment] 2019-03-17 03:00
Hi mate,

Issue number 3988

**Comment by glennguy** [comment] 2019-03-17 03:25
Thanks for that.

I've worked out what the issue is - we need to switch to the newer way of playing streams within Kodi which is available from version 17 onwards. Don't have time right now to implement it but hopefully within the next day or so.

**Comment by modano182** [comment] 2019-03-17 03:30
Mate you are an absolute legend. Thank you so much!

**Comment by hawksta** [comment] 2019-03-21 09:31
Is there a fix for this? I am having the same issue

**Comment by menzy81** [comment] 2019-03-21 09:32
I too am experiencing this on all 3 of my MiBox's running Kodi as of tonight (First game of the year) It was working through the JLT series.

No pressure @glennguy hehe

**Comment by glennguy** [comment] 2019-03-21 09:38
Hey guys

Working on it currently.

As it turns out, the changes from earlier this week have been overrided by the latest update from 2 days ago. The live streams now appear to be DRM protected, so @menzy81 I hope you're running Kodi 18 on all of your boxes!

Give me a few more minutes. I'll report back.

**Comment by randommonth** [comment] 2019-03-21 09:51
I'm seeing the same issue, running OSMC with 17.6. Glad to hear @glennguy is trying to fix it, I was worried this add-on was no longer supported! 

Hopefully OSMC finally updates to Kodi 18 soon...

**Comment by glennguy** [comment] 2019-03-21 10:13
Ok everyone v1.9.1 is now in the main repo, come and grab it!

**Closed by glennguy** 2019-03-21 10:13 UTC

**Comment by menzy81** [comment] 2019-03-21 10:32
@glennguy I have tried the zip file & it is working again thank you! Just a noob question, when will the addon auto update from the repo?

**Comment by glennguy** [comment] 2019-03-21 10:40
Not sure his often Kodi checks but definitely on a restart. Leave Auto update on as the new version is in the repo now.

**Comment by hawksta** [comment] 2019-03-21 10:49
What can i do of i do not want to upgrade to kodi 18, but stay with 17.6. If i upgrade i lose my build.

**Comment by glennguy** [comment] 2019-03-21 11:45
There's no staying with 17.6 and watching the live matches. Nothing we can do about that unfortunately.

**Comment by andybotting** [comment] 2019-03-21 20:35
@hawksta What's so special about your 'build'? Also, which platform are you running on?
